export const chains: Array<{[key:string]: any}> = [
    {
        "currency_symbol": "ETH",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "yes",
        "explorer_url": "https://etherscan.io/",
        "id": "1",
        "is_testnet": "no",
        "tags": ["ethereum", "eth", "mainnet"],
    },
    {
        "currency_symbol": "BNB",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "no",
        "explorer_url": "https://bscscan.com/",
        "id": "56",
        "is_testnet": "no",
        "tags": ["binance", "bnb", "bsc", "mainnet"],
    },
    {
        "currency_symbol": "MATIC",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "yes",
        "explorer_url": "https://polygonscan.com/",
        "id": "137",
        "is_testnet": "no",
        "tags": ["polygon", "matic", "mainnet"],
    },
    {
        "currency_symbol": "FTM",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "no",
        "explorer_url": "https://ftmscan.com/",
        "id": "250",
        "is_testnet": "no",
        "tags": ["fantom", "ftm", "mainnet"],
    },
    {
        "currency_symbol": "ETH",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "no",
        "explorer_url": "https://ropsten.etherscan.io/",
        "id": "3",
        "is_testnet": "yes",
        "tags": ["ethereum", "eth", "ropsten", "testnet"],
    },
    {
        "currency_symbol": "ETH",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "yes",
        "explorer_url": "https://goerli.etherscan.io/",
        "id": "5",
        "is_testnet": "yes",
        "tags": ["ethereum", "eth", "goerli", "testnet"],
    },
    {
        "currency_symbol": "MATIC",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "yes",
        "explorer_url": "https://mumbai.polygonscan.com/",
        "id": "80001",
        "is_testnet": "yes",
        "tags": ["polygon", "matic", "mumbai", "testnet"],
    },
    {
        "currency_symbol": "tBNB",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "yes",
        "explorer_url": "https://testnet.bscscan.com/",
        "id": "97",
        "is_testnet": "yes",
        "tags": ["binance", "bnb", "bsc", "testnet"],
    },
    {
        "currency_symbol": "FTM",
        "decimals_factor": "1.00000000000000e+18",
        "decimals": "18",
        "enabled": "yes",
        "explorer_url": "https://testnet.ftmscan.com/",
        "id": "4002",
        "is_testnet": "yes",
        "tags": ["fantom", "ftm", "testnet"],
    }
]